/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as ApiMapDataRouteImport } from './routes/api/map-data'
import { Route as ApiDesertAnalysisRouteImport } from './routes/api/desert-analysis'
import { Route as ApiAskRouteImport } from './routes/api/ask'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiMapDataRoute = ApiMapDataRouteImport.update({
  id: '/api/map-data',
  path: '/api/map-data',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiDesertAnalysisRoute = ApiDesertAnalysisRouteImport.update({
  id: '/api/desert-analysis',
  path: '/api/desert-analysis',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiAskRoute = ApiAskRouteImport.update({
  id: '/api/ask',
  path: '/api/ask',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/api/ask': typeof ApiAskRoute
  '/api/desert-analysis': typeof ApiDesertAnalysisRoute
  '/api/map-data': typeof ApiMapDataRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/api/ask': typeof ApiAskRoute
  '/api/desert-analysis': typeof ApiDesertAnalysisRoute
  '/api/map-data': typeof ApiMapDataRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/api/ask': typeof ApiAskRoute
  '/api/desert-analysis': typeof ApiDesertAnalysisRoute
  '/api/map-data': typeof ApiMapDataRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths: '/' | '/api/ask' | '/api/desert-analysis' | '/api/map-data'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/api/ask' | '/api/desert-analysis' | '/api/map-data'
  id: '__root__' | '/' | '/api/ask' | '/api/desert-analysis' | '/api/map-data'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  ApiAskRoute: typeof ApiAskRoute
  ApiDesertAnalysisRoute: typeof ApiDesertAnalysisRoute
  ApiMapDataRoute: typeof ApiMapDataRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/map-data': {
      id: '/api/map-data'
      path: '/api/map-data'
      fullPath: '/api/map-data'
      preLoaderRoute: typeof ApiMapDataRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/desert-analysis': {
      id: '/api/desert-analysis'
      path: '/api/desert-analysis'
      fullPath: '/api/desert-analysis'
      preLoaderRoute: typeof ApiDesertAnalysisRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/ask': {
      id: '/api/ask'
      path: '/api/ask'
      fullPath: '/api/ask'
      preLoaderRoute: typeof ApiAskRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  ApiAskRoute: ApiAskRoute,
  ApiDesertAnalysisRoute: ApiDesertAnalysisRoute,
  ApiMapDataRoute: ApiMapDataRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
